apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: demovpa
  namespace: demo
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: vpa
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: "vpa"
      minAllowed:
        cpu: "250m"
        memory: "150Mi"
      maxAllowed:
        cpu: "550m"
        memory: "600Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
   app: deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: deployment
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534 
      containers:
        - name: devops1
          image: ubuntu:latest
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 511m
              memory: 263Mi
          command: ["/bin/sh"]
          args:
            - "while true; do timeout 5s yes >/dev/null; sleep 5s; done"

